// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cep.proto

package br.com.evandrolacerda.grpc.grpc;

public final class Cep {
  private Cep() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CepRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CepRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string cep = 1;</code>
     */
    java.lang.String getCep();
    /**
     * <code>string cep = 1;</code>
     */
    com.google.protobuf.ByteString
        getCepBytes();
  }
  /**
   * Protobuf type {@code CepRequest}
   */
  public  static final class CepRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CepRequest)
      CepRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CepRequest.newBuilder() to construct.
    private CepRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CepRequest() {
      cep_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CepRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              cep_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.evandrolacerda.grpc.grpc.Cep.internal_static_CepRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.evandrolacerda.grpc.grpc.Cep.internal_static_CepRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.evandrolacerda.grpc.grpc.Cep.CepRequest.class, br.com.evandrolacerda.grpc.grpc.Cep.CepRequest.Builder.class);
    }

    public static final int CEP_FIELD_NUMBER = 1;
    private volatile java.lang.Object cep_;
    /**
     * <code>string cep = 1;</code>
     */
    public java.lang.String getCep() {
      java.lang.Object ref = cep_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cep_ = s;
        return s;
      }
    }
    /**
     * <code>string cep = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCepBytes() {
      java.lang.Object ref = cep_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cep_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCepBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cep_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCepBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cep_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.com.evandrolacerda.grpc.grpc.Cep.CepRequest)) {
        return super.equals(obj);
      }
      br.com.evandrolacerda.grpc.grpc.Cep.CepRequest other = (br.com.evandrolacerda.grpc.grpc.Cep.CepRequest) obj;

      boolean result = true;
      result = result && getCep()
          .equals(other.getCep());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CEP_FIELD_NUMBER;
      hash = (53 * hash) + getCep().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.com.evandrolacerda.grpc.grpc.Cep.CepRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.com.evandrolacerda.grpc.grpc.Cep.CepRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CepRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CepRequest)
        br.com.evandrolacerda.grpc.grpc.Cep.CepRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.com.evandrolacerda.grpc.grpc.Cep.internal_static_CepRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.com.evandrolacerda.grpc.grpc.Cep.internal_static_CepRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.com.evandrolacerda.grpc.grpc.Cep.CepRequest.class, br.com.evandrolacerda.grpc.grpc.Cep.CepRequest.Builder.class);
      }

      // Construct using br.com.evandrolacerda.grpc.grpc.Cep.CepRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cep_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.com.evandrolacerda.grpc.grpc.Cep.internal_static_CepRequest_descriptor;
      }

      @java.lang.Override
      public br.com.evandrolacerda.grpc.grpc.Cep.CepRequest getDefaultInstanceForType() {
        return br.com.evandrolacerda.grpc.grpc.Cep.CepRequest.getDefaultInstance();
      }

      @java.lang.Override
      public br.com.evandrolacerda.grpc.grpc.Cep.CepRequest build() {
        br.com.evandrolacerda.grpc.grpc.Cep.CepRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.com.evandrolacerda.grpc.grpc.Cep.CepRequest buildPartial() {
        br.com.evandrolacerda.grpc.grpc.Cep.CepRequest result = new br.com.evandrolacerda.grpc.grpc.Cep.CepRequest(this);
        result.cep_ = cep_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.com.evandrolacerda.grpc.grpc.Cep.CepRequest) {
          return mergeFrom((br.com.evandrolacerda.grpc.grpc.Cep.CepRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.com.evandrolacerda.grpc.grpc.Cep.CepRequest other) {
        if (other == br.com.evandrolacerda.grpc.grpc.Cep.CepRequest.getDefaultInstance()) return this;
        if (!other.getCep().isEmpty()) {
          cep_ = other.cep_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.com.evandrolacerda.grpc.grpc.Cep.CepRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.com.evandrolacerda.grpc.grpc.Cep.CepRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object cep_ = "";
      /**
       * <code>string cep = 1;</code>
       */
      public java.lang.String getCep() {
        java.lang.Object ref = cep_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cep_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cep = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCepBytes() {
        java.lang.Object ref = cep_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cep_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cep = 1;</code>
       */
      public Builder setCep(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cep_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cep = 1;</code>
       */
      public Builder clearCep() {
        
        cep_ = getDefaultInstance().getCep();
        onChanged();
        return this;
      }
      /**
       * <code>string cep = 1;</code>
       */
      public Builder setCepBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cep_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CepRequest)
    }

    // @@protoc_insertion_point(class_scope:CepRequest)
    private static final br.com.evandrolacerda.grpc.grpc.Cep.CepRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.com.evandrolacerda.grpc.grpc.Cep.CepRequest();
    }

    public static br.com.evandrolacerda.grpc.grpc.Cep.CepRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CepRequest>
        PARSER = new com.google.protobuf.AbstractParser<CepRequest>() {
      @java.lang.Override
      public CepRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CepRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CepRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CepRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.com.evandrolacerda.grpc.grpc.Cep.CepRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CepResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CepResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string cep = 1;</code>
     */
    java.lang.String getCep();
    /**
     * <code>string cep = 1;</code>
     */
    com.google.protobuf.ByteString
        getCepBytes();

    /**
     * <code>string logradouro = 2;</code>
     */
    java.lang.String getLogradouro();
    /**
     * <code>string logradouro = 2;</code>
     */
    com.google.protobuf.ByteString
        getLogradouroBytes();

    /**
     * <code>string complemento = 3;</code>
     */
    java.lang.String getComplemento();
    /**
     * <code>string complemento = 3;</code>
     */
    com.google.protobuf.ByteString
        getComplementoBytes();

    /**
     * <code>string bairro = 4;</code>
     */
    java.lang.String getBairro();
    /**
     * <code>string bairro = 4;</code>
     */
    com.google.protobuf.ByteString
        getBairroBytes();

    /**
     * <code>string localidade = 5;</code>
     */
    java.lang.String getLocalidade();
    /**
     * <code>string localidade = 5;</code>
     */
    com.google.protobuf.ByteString
        getLocalidadeBytes();

    /**
     * <code>string uf = 6;</code>
     */
    java.lang.String getUf();
    /**
     * <code>string uf = 6;</code>
     */
    com.google.protobuf.ByteString
        getUfBytes();

    /**
     * <code>string ibge = 7;</code>
     */
    java.lang.String getIbge();
    /**
     * <code>string ibge = 7;</code>
     */
    com.google.protobuf.ByteString
        getIbgeBytes();

    /**
     * <code>string gia = 8;</code>
     */
    java.lang.String getGia();
    /**
     * <code>string gia = 8;</code>
     */
    com.google.protobuf.ByteString
        getGiaBytes();

    /**
     * <code>string ddd = 9;</code>
     */
    java.lang.String getDdd();
    /**
     * <code>string ddd = 9;</code>
     */
    com.google.protobuf.ByteString
        getDddBytes();

    /**
     * <code>string siafi = 10;</code>
     */
    java.lang.String getSiafi();
    /**
     * <code>string siafi = 10;</code>
     */
    com.google.protobuf.ByteString
        getSiafiBytes();
  }
  /**
   * Protobuf type {@code CepResponse}
   */
  public  static final class CepResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CepResponse)
      CepResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CepResponse.newBuilder() to construct.
    private CepResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CepResponse() {
      cep_ = "";
      logradouro_ = "";
      complemento_ = "";
      bairro_ = "";
      localidade_ = "";
      uf_ = "";
      ibge_ = "";
      gia_ = "";
      ddd_ = "";
      siafi_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CepResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              cep_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              logradouro_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              complemento_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              bairro_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              localidade_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              uf_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              ibge_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              gia_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              ddd_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              siafi_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.evandrolacerda.grpc.grpc.Cep.internal_static_CepResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.evandrolacerda.grpc.grpc.Cep.internal_static_CepResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.evandrolacerda.grpc.grpc.Cep.CepResponse.class, br.com.evandrolacerda.grpc.grpc.Cep.CepResponse.Builder.class);
    }

    public static final int CEP_FIELD_NUMBER = 1;
    private volatile java.lang.Object cep_;
    /**
     * <code>string cep = 1;</code>
     */
    public java.lang.String getCep() {
      java.lang.Object ref = cep_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cep_ = s;
        return s;
      }
    }
    /**
     * <code>string cep = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCepBytes() {
      java.lang.Object ref = cep_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cep_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGRADOURO_FIELD_NUMBER = 2;
    private volatile java.lang.Object logradouro_;
    /**
     * <code>string logradouro = 2;</code>
     */
    public java.lang.String getLogradouro() {
      java.lang.Object ref = logradouro_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logradouro_ = s;
        return s;
      }
    }
    /**
     * <code>string logradouro = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLogradouroBytes() {
      java.lang.Object ref = logradouro_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logradouro_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPLEMENTO_FIELD_NUMBER = 3;
    private volatile java.lang.Object complemento_;
    /**
     * <code>string complemento = 3;</code>
     */
    public java.lang.String getComplemento() {
      java.lang.Object ref = complemento_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        complemento_ = s;
        return s;
      }
    }
    /**
     * <code>string complemento = 3;</code>
     */
    public com.google.protobuf.ByteString
        getComplementoBytes() {
      java.lang.Object ref = complemento_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        complemento_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BAIRRO_FIELD_NUMBER = 4;
    private volatile java.lang.Object bairro_;
    /**
     * <code>string bairro = 4;</code>
     */
    public java.lang.String getBairro() {
      java.lang.Object ref = bairro_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bairro_ = s;
        return s;
      }
    }
    /**
     * <code>string bairro = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBairroBytes() {
      java.lang.Object ref = bairro_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bairro_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCALIDADE_FIELD_NUMBER = 5;
    private volatile java.lang.Object localidade_;
    /**
     * <code>string localidade = 5;</code>
     */
    public java.lang.String getLocalidade() {
      java.lang.Object ref = localidade_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localidade_ = s;
        return s;
      }
    }
    /**
     * <code>string localidade = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLocalidadeBytes() {
      java.lang.Object ref = localidade_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localidade_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UF_FIELD_NUMBER = 6;
    private volatile java.lang.Object uf_;
    /**
     * <code>string uf = 6;</code>
     */
    public java.lang.String getUf() {
      java.lang.Object ref = uf_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uf_ = s;
        return s;
      }
    }
    /**
     * <code>string uf = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUfBytes() {
      java.lang.Object ref = uf_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IBGE_FIELD_NUMBER = 7;
    private volatile java.lang.Object ibge_;
    /**
     * <code>string ibge = 7;</code>
     */
    public java.lang.String getIbge() {
      java.lang.Object ref = ibge_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ibge_ = s;
        return s;
      }
    }
    /**
     * <code>string ibge = 7;</code>
     */
    public com.google.protobuf.ByteString
        getIbgeBytes() {
      java.lang.Object ref = ibge_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ibge_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GIA_FIELD_NUMBER = 8;
    private volatile java.lang.Object gia_;
    /**
     * <code>string gia = 8;</code>
     */
    public java.lang.String getGia() {
      java.lang.Object ref = gia_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gia_ = s;
        return s;
      }
    }
    /**
     * <code>string gia = 8;</code>
     */
    public com.google.protobuf.ByteString
        getGiaBytes() {
      java.lang.Object ref = gia_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gia_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DDD_FIELD_NUMBER = 9;
    private volatile java.lang.Object ddd_;
    /**
     * <code>string ddd = 9;</code>
     */
    public java.lang.String getDdd() {
      java.lang.Object ref = ddd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ddd_ = s;
        return s;
      }
    }
    /**
     * <code>string ddd = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDddBytes() {
      java.lang.Object ref = ddd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ddd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIAFI_FIELD_NUMBER = 10;
    private volatile java.lang.Object siafi_;
    /**
     * <code>string siafi = 10;</code>
     */
    public java.lang.String getSiafi() {
      java.lang.Object ref = siafi_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siafi_ = s;
        return s;
      }
    }
    /**
     * <code>string siafi = 10;</code>
     */
    public com.google.protobuf.ByteString
        getSiafiBytes() {
      java.lang.Object ref = siafi_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siafi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCepBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cep_);
      }
      if (!getLogradouroBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, logradouro_);
      }
      if (!getComplementoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, complemento_);
      }
      if (!getBairroBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, bairro_);
      }
      if (!getLocalidadeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, localidade_);
      }
      if (!getUfBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, uf_);
      }
      if (!getIbgeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, ibge_);
      }
      if (!getGiaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, gia_);
      }
      if (!getDddBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, ddd_);
      }
      if (!getSiafiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, siafi_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCepBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cep_);
      }
      if (!getLogradouroBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, logradouro_);
      }
      if (!getComplementoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, complemento_);
      }
      if (!getBairroBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, bairro_);
      }
      if (!getLocalidadeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, localidade_);
      }
      if (!getUfBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, uf_);
      }
      if (!getIbgeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, ibge_);
      }
      if (!getGiaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, gia_);
      }
      if (!getDddBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, ddd_);
      }
      if (!getSiafiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, siafi_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.com.evandrolacerda.grpc.grpc.Cep.CepResponse)) {
        return super.equals(obj);
      }
      br.com.evandrolacerda.grpc.grpc.Cep.CepResponse other = (br.com.evandrolacerda.grpc.grpc.Cep.CepResponse) obj;

      boolean result = true;
      result = result && getCep()
          .equals(other.getCep());
      result = result && getLogradouro()
          .equals(other.getLogradouro());
      result = result && getComplemento()
          .equals(other.getComplemento());
      result = result && getBairro()
          .equals(other.getBairro());
      result = result && getLocalidade()
          .equals(other.getLocalidade());
      result = result && getUf()
          .equals(other.getUf());
      result = result && getIbge()
          .equals(other.getIbge());
      result = result && getGia()
          .equals(other.getGia());
      result = result && getDdd()
          .equals(other.getDdd());
      result = result && getSiafi()
          .equals(other.getSiafi());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CEP_FIELD_NUMBER;
      hash = (53 * hash) + getCep().hashCode();
      hash = (37 * hash) + LOGRADOURO_FIELD_NUMBER;
      hash = (53 * hash) + getLogradouro().hashCode();
      hash = (37 * hash) + COMPLEMENTO_FIELD_NUMBER;
      hash = (53 * hash) + getComplemento().hashCode();
      hash = (37 * hash) + BAIRRO_FIELD_NUMBER;
      hash = (53 * hash) + getBairro().hashCode();
      hash = (37 * hash) + LOCALIDADE_FIELD_NUMBER;
      hash = (53 * hash) + getLocalidade().hashCode();
      hash = (37 * hash) + UF_FIELD_NUMBER;
      hash = (53 * hash) + getUf().hashCode();
      hash = (37 * hash) + IBGE_FIELD_NUMBER;
      hash = (53 * hash) + getIbge().hashCode();
      hash = (37 * hash) + GIA_FIELD_NUMBER;
      hash = (53 * hash) + getGia().hashCode();
      hash = (37 * hash) + DDD_FIELD_NUMBER;
      hash = (53 * hash) + getDdd().hashCode();
      hash = (37 * hash) + SIAFI_FIELD_NUMBER;
      hash = (53 * hash) + getSiafi().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.com.evandrolacerda.grpc.grpc.Cep.CepResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.com.evandrolacerda.grpc.grpc.Cep.CepResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.com.evandrolacerda.grpc.grpc.Cep.CepResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CepResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CepResponse)
        br.com.evandrolacerda.grpc.grpc.Cep.CepResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.com.evandrolacerda.grpc.grpc.Cep.internal_static_CepResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.com.evandrolacerda.grpc.grpc.Cep.internal_static_CepResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.com.evandrolacerda.grpc.grpc.Cep.CepResponse.class, br.com.evandrolacerda.grpc.grpc.Cep.CepResponse.Builder.class);
      }

      // Construct using br.com.evandrolacerda.grpc.grpc.Cep.CepResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cep_ = "";

        logradouro_ = "";

        complemento_ = "";

        bairro_ = "";

        localidade_ = "";

        uf_ = "";

        ibge_ = "";

        gia_ = "";

        ddd_ = "";

        siafi_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.com.evandrolacerda.grpc.grpc.Cep.internal_static_CepResponse_descriptor;
      }

      @java.lang.Override
      public br.com.evandrolacerda.grpc.grpc.Cep.CepResponse getDefaultInstanceForType() {
        return br.com.evandrolacerda.grpc.grpc.Cep.CepResponse.getDefaultInstance();
      }

      @java.lang.Override
      public br.com.evandrolacerda.grpc.grpc.Cep.CepResponse build() {
        br.com.evandrolacerda.grpc.grpc.Cep.CepResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.com.evandrolacerda.grpc.grpc.Cep.CepResponse buildPartial() {
        br.com.evandrolacerda.grpc.grpc.Cep.CepResponse result = new br.com.evandrolacerda.grpc.grpc.Cep.CepResponse(this);
        result.cep_ = cep_;
        result.logradouro_ = logradouro_;
        result.complemento_ = complemento_;
        result.bairro_ = bairro_;
        result.localidade_ = localidade_;
        result.uf_ = uf_;
        result.ibge_ = ibge_;
        result.gia_ = gia_;
        result.ddd_ = ddd_;
        result.siafi_ = siafi_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.com.evandrolacerda.grpc.grpc.Cep.CepResponse) {
          return mergeFrom((br.com.evandrolacerda.grpc.grpc.Cep.CepResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.com.evandrolacerda.grpc.grpc.Cep.CepResponse other) {
        if (other == br.com.evandrolacerda.grpc.grpc.Cep.CepResponse.getDefaultInstance()) return this;
        if (!other.getCep().isEmpty()) {
          cep_ = other.cep_;
          onChanged();
        }
        if (!other.getLogradouro().isEmpty()) {
          logradouro_ = other.logradouro_;
          onChanged();
        }
        if (!other.getComplemento().isEmpty()) {
          complemento_ = other.complemento_;
          onChanged();
        }
        if (!other.getBairro().isEmpty()) {
          bairro_ = other.bairro_;
          onChanged();
        }
        if (!other.getLocalidade().isEmpty()) {
          localidade_ = other.localidade_;
          onChanged();
        }
        if (!other.getUf().isEmpty()) {
          uf_ = other.uf_;
          onChanged();
        }
        if (!other.getIbge().isEmpty()) {
          ibge_ = other.ibge_;
          onChanged();
        }
        if (!other.getGia().isEmpty()) {
          gia_ = other.gia_;
          onChanged();
        }
        if (!other.getDdd().isEmpty()) {
          ddd_ = other.ddd_;
          onChanged();
        }
        if (!other.getSiafi().isEmpty()) {
          siafi_ = other.siafi_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.com.evandrolacerda.grpc.grpc.Cep.CepResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.com.evandrolacerda.grpc.grpc.Cep.CepResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object cep_ = "";
      /**
       * <code>string cep = 1;</code>
       */
      public java.lang.String getCep() {
        java.lang.Object ref = cep_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cep_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cep = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCepBytes() {
        java.lang.Object ref = cep_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cep_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cep = 1;</code>
       */
      public Builder setCep(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cep_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cep = 1;</code>
       */
      public Builder clearCep() {
        
        cep_ = getDefaultInstance().getCep();
        onChanged();
        return this;
      }
      /**
       * <code>string cep = 1;</code>
       */
      public Builder setCepBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cep_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object logradouro_ = "";
      /**
       * <code>string logradouro = 2;</code>
       */
      public java.lang.String getLogradouro() {
        java.lang.Object ref = logradouro_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logradouro_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string logradouro = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLogradouroBytes() {
        java.lang.Object ref = logradouro_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logradouro_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string logradouro = 2;</code>
       */
      public Builder setLogradouro(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logradouro_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string logradouro = 2;</code>
       */
      public Builder clearLogradouro() {
        
        logradouro_ = getDefaultInstance().getLogradouro();
        onChanged();
        return this;
      }
      /**
       * <code>string logradouro = 2;</code>
       */
      public Builder setLogradouroBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logradouro_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object complemento_ = "";
      /**
       * <code>string complemento = 3;</code>
       */
      public java.lang.String getComplemento() {
        java.lang.Object ref = complemento_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          complemento_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string complemento = 3;</code>
       */
      public com.google.protobuf.ByteString
          getComplementoBytes() {
        java.lang.Object ref = complemento_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          complemento_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string complemento = 3;</code>
       */
      public Builder setComplemento(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        complemento_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string complemento = 3;</code>
       */
      public Builder clearComplemento() {
        
        complemento_ = getDefaultInstance().getComplemento();
        onChanged();
        return this;
      }
      /**
       * <code>string complemento = 3;</code>
       */
      public Builder setComplementoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        complemento_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bairro_ = "";
      /**
       * <code>string bairro = 4;</code>
       */
      public java.lang.String getBairro() {
        java.lang.Object ref = bairro_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bairro_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bairro = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBairroBytes() {
        java.lang.Object ref = bairro_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bairro_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bairro = 4;</code>
       */
      public Builder setBairro(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bairro_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bairro = 4;</code>
       */
      public Builder clearBairro() {
        
        bairro_ = getDefaultInstance().getBairro();
        onChanged();
        return this;
      }
      /**
       * <code>string bairro = 4;</code>
       */
      public Builder setBairroBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bairro_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object localidade_ = "";
      /**
       * <code>string localidade = 5;</code>
       */
      public java.lang.String getLocalidade() {
        java.lang.Object ref = localidade_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          localidade_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string localidade = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLocalidadeBytes() {
        java.lang.Object ref = localidade_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localidade_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string localidade = 5;</code>
       */
      public Builder setLocalidade(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        localidade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string localidade = 5;</code>
       */
      public Builder clearLocalidade() {
        
        localidade_ = getDefaultInstance().getLocalidade();
        onChanged();
        return this;
      }
      /**
       * <code>string localidade = 5;</code>
       */
      public Builder setLocalidadeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        localidade_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object uf_ = "";
      /**
       * <code>string uf = 6;</code>
       */
      public java.lang.String getUf() {
        java.lang.Object ref = uf_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uf_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uf = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUfBytes() {
        java.lang.Object ref = uf_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uf_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uf = 6;</code>
       */
      public Builder setUf(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uf = 6;</code>
       */
      public Builder clearUf() {
        
        uf_ = getDefaultInstance().getUf();
        onChanged();
        return this;
      }
      /**
       * <code>string uf = 6;</code>
       */
      public Builder setUfBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uf_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ibge_ = "";
      /**
       * <code>string ibge = 7;</code>
       */
      public java.lang.String getIbge() {
        java.lang.Object ref = ibge_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ibge_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ibge = 7;</code>
       */
      public com.google.protobuf.ByteString
          getIbgeBytes() {
        java.lang.Object ref = ibge_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ibge_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ibge = 7;</code>
       */
      public Builder setIbge(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ibge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ibge = 7;</code>
       */
      public Builder clearIbge() {
        
        ibge_ = getDefaultInstance().getIbge();
        onChanged();
        return this;
      }
      /**
       * <code>string ibge = 7;</code>
       */
      public Builder setIbgeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ibge_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gia_ = "";
      /**
       * <code>string gia = 8;</code>
       */
      public java.lang.String getGia() {
        java.lang.Object ref = gia_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gia_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gia = 8;</code>
       */
      public com.google.protobuf.ByteString
          getGiaBytes() {
        java.lang.Object ref = gia_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gia_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gia = 8;</code>
       */
      public Builder setGia(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gia_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gia = 8;</code>
       */
      public Builder clearGia() {
        
        gia_ = getDefaultInstance().getGia();
        onChanged();
        return this;
      }
      /**
       * <code>string gia = 8;</code>
       */
      public Builder setGiaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gia_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ddd_ = "";
      /**
       * <code>string ddd = 9;</code>
       */
      public java.lang.String getDdd() {
        java.lang.Object ref = ddd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ddd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ddd = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDddBytes() {
        java.lang.Object ref = ddd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ddd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ddd = 9;</code>
       */
      public Builder setDdd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ddd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ddd = 9;</code>
       */
      public Builder clearDdd() {
        
        ddd_ = getDefaultInstance().getDdd();
        onChanged();
        return this;
      }
      /**
       * <code>string ddd = 9;</code>
       */
      public Builder setDddBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ddd_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object siafi_ = "";
      /**
       * <code>string siafi = 10;</code>
       */
      public java.lang.String getSiafi() {
        java.lang.Object ref = siafi_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siafi_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string siafi = 10;</code>
       */
      public com.google.protobuf.ByteString
          getSiafiBytes() {
        java.lang.Object ref = siafi_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siafi_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string siafi = 10;</code>
       */
      public Builder setSiafi(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siafi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string siafi = 10;</code>
       */
      public Builder clearSiafi() {
        
        siafi_ = getDefaultInstance().getSiafi();
        onChanged();
        return this;
      }
      /**
       * <code>string siafi = 10;</code>
       */
      public Builder setSiafiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siafi_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CepResponse)
    }

    // @@protoc_insertion_point(class_scope:CepResponse)
    private static final br.com.evandrolacerda.grpc.grpc.Cep.CepResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.com.evandrolacerda.grpc.grpc.Cep.CepResponse();
    }

    public static br.com.evandrolacerda.grpc.grpc.Cep.CepResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CepResponse>
        PARSER = new com.google.protobuf.AbstractParser<CepResponse>() {
      @java.lang.Override
      public CepResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CepResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CepResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CepResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.com.evandrolacerda.grpc.grpc.Cep.CepResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CepRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CepRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CepResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CepResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcep.proto\"\031\n\nCepRequest\022\013\n\003cep\030\001 \001(\t\"\252" +
      "\001\n\013CepResponse\022\013\n\003cep\030\001 \001(\t\022\022\n\nlogradour" +
      "o\030\002 \001(\t\022\023\n\013complemento\030\003 \001(\t\022\016\n\006bairro\030\004" +
      " \001(\t\022\022\n\nlocalidade\030\005 \001(\t\022\n\n\002uf\030\006 \001(\t\022\014\n\004" +
      "ibge\030\007 \001(\t\022\013\n\003gia\030\010 \001(\t\022\013\n\003ddd\030\t \001(\t\022\r\n\005" +
      "siafi\030\n \001(\t2,\n\003cep\022%\n\006GetCep\022\013.CepReques" +
      "t\032\014.CepResponse\"\000B!\n\037br.com.evandrolacer" +
      "da.grpc.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CepRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CepRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CepRequest_descriptor,
        new java.lang.String[] { "Cep", });
    internal_static_CepResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CepResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CepResponse_descriptor,
        new java.lang.String[] { "Cep", "Logradouro", "Complemento", "Bairro", "Localidade", "Uf", "Ibge", "Gia", "Ddd", "Siafi", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
